### ISSUE TITLE
Invalid state for the new form

### ISSUE THREAD

**Issue by kmmbvnr** [Volicon/NestedLink#5]
It's pretty uncommon to see error messages on empty new form.

Ex in user list example, as soon as Add user button clicked.

![nestedreact todomvc](https://cloud.githubusercontent.com/assets/282529/15175076/812a3184-1786-11e6-8e46-47bcddc144b9.png)

Is there any way in valuelink library to postpone the validation till user navigates out of the field, or press submit button?

**Comment by gaperton** [comment]
Sure you can. Like this:
1) Add 'ingnoreIsRequired' attribute to the state, and set it to true in onSubmit handler.
2) In "is required" validation checks, instead of x => x it should be x => ignoreIsRequired || x
3) In the next checks emptiness guards are needed.
4) In submit button, you have to manually detect whenever required state members are empty.

**Comment by gaperton** [comment]
But I don't see any advantage in not telling the user from the beginning which fields are required.

What I would probably done if our QA would be bothered, is introducing different styles for error messages. Because, `error` can have any shape.

.check( x => x, { type : 'required', name : 'Name' })

Then, I would modify Input controls so they will style different error types differently.

**Comment by gaperton** [comment]
To do it in better way you need something more advanced than plain React state. Problem here is that checks is not attached to the state, they are inlined in render(). Which is okay for many cases, but you cannot run checks outside of `render`.

If you use models instead of the state, you can.

https://github.com/Volicon/NestedReact#link-validation

**Comment by gaperton** [comment]
Whenever input value is an empty string, and validation fails, it will add 'required' class to the input control. Thus, you will have an opportunity to mark it differently. With yellow, for example. Changes now in 'develop' branch.

Thanks for the bug, it's was really the good point.
